// Icon catalog using Material Design Icons (MDI)
// Browse all: https://icon-sets.iconify.design/mdi/

export interface IconEntry {
  name: string
  /** MDI icon name in kebab-case (used as mdi:{filename}) */
  filename: string
  category: string
}

export const ICON_CATEGORIES = [
  'Actions',
  'Arrows',
  'Communication',
  'Commerce',
  'Content',
  'Device',
  'Files',
  'Health',
  'Home',
  'Maps',
  'Media',
  'Navigation',
  'People',
  'Social',
  'System',
  'Weather',
] as const

export type IconCategory = (typeof ICON_CATEGORIES)[number]

export const ICONS: IconEntry[] = [
  // ── Actions ──────────────────────────────────────────────
  { name: 'Add', filename: 'plus', category: 'Actions' },
  { name: 'Remove', filename: 'minus', category: 'Actions' },
  { name: 'Close', filename: 'close', category: 'Actions' },
  { name: 'Check', filename: 'check', category: 'Actions' },
  { name: 'Delete', filename: 'delete', category: 'Actions' },
  { name: 'Edit', filename: 'pencil', category: 'Actions' },
  { name: 'Search', filename: 'magnify', category: 'Actions' },
  { name: 'Filter', filename: 'filter-variant', category: 'Actions' },
  { name: 'Sort', filename: 'sort', category: 'Actions' },
  { name: 'Copy', filename: 'content-copy', category: 'Actions' },
  { name: 'Cut', filename: 'content-cut', category: 'Actions' },
  { name: 'Paste', filename: 'content-paste', category: 'Actions' },
  { name: 'Share', filename: 'share-variant', category: 'Actions' },
  { name: 'Download', filename: 'download', category: 'Actions' },
  { name: 'Upload', filename: 'upload', category: 'Actions' },
  { name: 'Refresh', filename: 'refresh', category: 'Actions' },
  { name: 'Undo', filename: 'undo', category: 'Actions' },
  { name: 'Redo', filename: 'redo', category: 'Actions' },
  { name: 'Save', filename: 'content-save', category: 'Actions' },
  { name: 'Print', filename: 'printer', category: 'Actions' },
  { name: 'Settings', filename: 'cog', category: 'Actions' },
  { name: 'Tune', filename: 'tune', category: 'Actions' },
  { name: 'More Vertical', filename: 'dots-vertical', category: 'Actions' },
  { name: 'More Horizontal', filename: 'dots-horizontal', category: 'Actions' },
  { name: 'Drag Handle', filename: 'drag', category: 'Actions' },
  { name: 'Expand', filename: 'arrow-expand', category: 'Actions' },
  { name: 'Collapse', filename: 'arrow-collapse', category: 'Actions' },
  { name: 'Fullscreen', filename: 'fullscreen', category: 'Actions' },
  { name: 'Fullscreen Exit', filename: 'fullscreen-exit', category: 'Actions' },
  { name: 'Open In New', filename: 'open-in-new', category: 'Actions' },
  { name: 'Launch', filename: 'launch', category: 'Actions' },
  { name: 'Power', filename: 'power', category: 'Actions' },
  { name: 'Logout', filename: 'logout', category: 'Actions' },
  { name: 'Login', filename: 'login', category: 'Actions' },
  { name: 'Lock', filename: 'lock', category: 'Actions' },
  { name: 'Lock Open', filename: 'lock-open', category: 'Actions' },
  { name: 'Pin', filename: 'pin', category: 'Actions' },
  { name: 'Pin Off', filename: 'pin-off', category: 'Actions' },
  { name: 'Bookmark', filename: 'bookmark', category: 'Actions' },
  { name: 'Bookmark Outline', filename: 'bookmark-outline', category: 'Actions' },
  { name: 'Star', filename: 'star', category: 'Actions' },
  { name: 'Star Outline', filename: 'star-outline', category: 'Actions' },
  { name: 'Heart', filename: 'heart', category: 'Actions' },
  { name: 'Heart Outline', filename: 'heart-outline', category: 'Actions' },
  { name: 'Thumb Up', filename: 'thumb-up', category: 'Actions' },
  { name: 'Thumb Down', filename: 'thumb-down', category: 'Actions' },
  { name: 'Flag', filename: 'flag', category: 'Actions' },
  { name: 'Flag Outline', filename: 'flag-outline', category: 'Actions' },
  { name: 'Archive', filename: 'archive', category: 'Actions' },
  { name: 'Trash Can', filename: 'trash-can', category: 'Actions' },

  // ── Arrows ───────────────────────────────────────────────
  { name: 'Arrow Up', filename: 'arrow-up', category: 'Arrows' },
  { name: 'Arrow Down', filename: 'arrow-down', category: 'Arrows' },
  { name: 'Arrow Left', filename: 'arrow-left', category: 'Arrows' },
  { name: 'Arrow Right', filename: 'arrow-right', category: 'Arrows' },
  { name: 'Arrow Up Bold', filename: 'arrow-up-bold', category: 'Arrows' },
  { name: 'Arrow Down Bold', filename: 'arrow-down-bold', category: 'Arrows' },
  { name: 'Arrow Left Bold', filename: 'arrow-left-bold', category: 'Arrows' },
  { name: 'Arrow Right Bold', filename: 'arrow-right-bold', category: 'Arrows' },
  { name: 'Chevron Up', filename: 'chevron-up', category: 'Arrows' },
  { name: 'Chevron Down', filename: 'chevron-down', category: 'Arrows' },
  { name: 'Chevron Left', filename: 'chevron-left', category: 'Arrows' },
  { name: 'Chevron Right', filename: 'chevron-right', category: 'Arrows' },
  { name: 'Double Chevron Up', filename: 'chevron-double-up', category: 'Arrows' },
  { name: 'Double Chevron Down', filename: 'chevron-double-down', category: 'Arrows' },
  { name: 'Double Chevron Left', filename: 'chevron-double-left', category: 'Arrows' },
  { name: 'Double Chevron Right', filename: 'chevron-double-right', category: 'Arrows' },
  { name: 'Arrow Top Right', filename: 'arrow-top-right', category: 'Arrows' },
  { name: 'Arrow Bottom Right', filename: 'arrow-bottom-right', category: 'Arrows' },
  { name: 'Arrow Swap', filename: 'swap-horizontal', category: 'Arrows' },
  { name: 'Arrow Swap Vertical', filename: 'swap-vertical', category: 'Arrows' },
  { name: 'Subdirectory', filename: 'subdirectory-arrow-right', category: 'Arrows' },
  { name: 'Reply', filename: 'reply', category: 'Arrows' },
  { name: 'Forward', filename: 'forward', category: 'Arrows' },

  // ── Communication ────────────────────────────────────────
  { name: 'Email', filename: 'email', category: 'Communication' },
  { name: 'Email Outline', filename: 'email-outline', category: 'Communication' },
  { name: 'Chat', filename: 'chat', category: 'Communication' },
  { name: 'Chat Outline', filename: 'chat-outline', category: 'Communication' },
  { name: 'Message', filename: 'message', category: 'Communication' },
  { name: 'Message Outline', filename: 'message-outline', category: 'Communication' },
  { name: 'Phone', filename: 'phone', category: 'Communication' },
  { name: 'Phone Outline', filename: 'phone-outline', category: 'Communication' },
  { name: 'Video', filename: 'video', category: 'Communication' },
  { name: 'Bell', filename: 'bell', category: 'Communication' },
  { name: 'Bell Outline', filename: 'bell-outline', category: 'Communication' },
  { name: 'Bell Off', filename: 'bell-off', category: 'Communication' },
  { name: 'Send', filename: 'send', category: 'Communication' },
  { name: 'Inbox', filename: 'inbox', category: 'Communication' },
  { name: 'Forum', filename: 'forum', category: 'Communication' },

  // ── Commerce ─────────────────────────────────────────────
  { name: 'Cart', filename: 'cart', category: 'Commerce' },
  { name: 'Cart Outline', filename: 'cart-outline', category: 'Commerce' },
  { name: 'Basket', filename: 'basket', category: 'Commerce' },
  { name: 'Store', filename: 'store', category: 'Commerce' },
  { name: 'Store Outline', filename: 'store-outline', category: 'Commerce' },
  { name: 'Credit Card', filename: 'credit-card', category: 'Commerce' },
  { name: 'Credit Card Outline', filename: 'credit-card-outline', category: 'Commerce' },
  { name: 'Cash', filename: 'cash', category: 'Commerce' },
  { name: 'Currency USD', filename: 'currency-usd', category: 'Commerce' },
  { name: 'Wallet', filename: 'wallet', category: 'Commerce' },
  { name: 'Receipt', filename: 'receipt', category: 'Commerce' },
  { name: 'Tag', filename: 'tag', category: 'Commerce' },
  { name: 'Tag Outline', filename: 'tag-outline', category: 'Commerce' },
  { name: 'Percent', filename: 'percent', category: 'Commerce' },
  { name: 'Gift', filename: 'gift', category: 'Commerce' },
  { name: 'Barcode', filename: 'barcode', category: 'Commerce' },
  { name: 'QR Code', filename: 'qrcode', category: 'Commerce' },

  // ── Content ──────────────────────────────────────────────
  { name: 'Text', filename: 'format-text', category: 'Content' },
  { name: 'Bold', filename: 'format-bold', category: 'Content' },
  { name: 'Italic', filename: 'format-italic', category: 'Content' },
  { name: 'Underline', filename: 'format-underline', category: 'Content' },
  { name: 'Strikethrough', filename: 'format-strikethrough', category: 'Content' },
  { name: 'List Bulleted', filename: 'format-list-bulleted', category: 'Content' },
  { name: 'List Numbered', filename: 'format-list-numbered', category: 'Content' },
  { name: 'Quote', filename: 'format-quote-close', category: 'Content' },
  { name: 'Link', filename: 'link', category: 'Content' },
  { name: 'Link Off', filename: 'link-off', category: 'Content' },
  { name: 'Attachment', filename: 'attachment', category: 'Content' },
  { name: 'Code Tags', filename: 'code-tags', category: 'Content' },

  // ── Device ───────────────────────────────────────────────
  { name: 'Phone Portrait', filename: 'cellphone', category: 'Device' },
  { name: 'Tablet', filename: 'tablet', category: 'Device' },
  { name: 'Laptop', filename: 'laptop', category: 'Device' },
  { name: 'Desktop', filename: 'monitor', category: 'Device' },
  { name: 'Watch', filename: 'watch', category: 'Device' },
  { name: 'Keyboard', filename: 'keyboard', category: 'Device' },
  { name: 'Mouse', filename: 'mouse', category: 'Device' },
  { name: 'Bluetooth', filename: 'bluetooth', category: 'Device' },
  { name: 'Wifi', filename: 'wifi', category: 'Device' },
  { name: 'Battery', filename: 'battery', category: 'Device' },
  { name: 'USB', filename: 'usb', category: 'Device' },
  { name: 'Camera', filename: 'camera', category: 'Device' },
  { name: 'Camera Outline', filename: 'camera-outline', category: 'Device' },
  { name: 'QR Code Scan', filename: 'qrcode-scan', category: 'Device' },
  { name: 'Fingerprint', filename: 'fingerprint', category: 'Device' },

  // ── Files ────────────────────────────────────────────────
  { name: 'File', filename: 'file', category: 'Files' },
  { name: 'File Outline', filename: 'file-outline', category: 'Files' },
  { name: 'File Document', filename: 'file-document', category: 'Files' },
  { name: 'File Image', filename: 'file-image', category: 'Files' },
  { name: 'File PDF', filename: 'file-pdf-box', category: 'Files' },
  { name: 'Folder', filename: 'folder', category: 'Files' },
  { name: 'Folder Outline', filename: 'folder-outline', category: 'Files' },
  { name: 'Folder Open', filename: 'folder-open', category: 'Files' },
  { name: 'Cloud', filename: 'cloud', category: 'Files' },
  { name: 'Cloud Upload', filename: 'cloud-upload', category: 'Files' },
  { name: 'Cloud Download', filename: 'cloud-download', category: 'Files' },

  // ── Health ───────────────────────────────────────────────
  { name: 'Heart Pulse', filename: 'heart-pulse', category: 'Health' },
  { name: 'Hospital', filename: 'hospital-building', category: 'Health' },
  { name: 'Pill', filename: 'pill', category: 'Health' },
  { name: 'Stethoscope', filename: 'stethoscope', category: 'Health' },
  { name: 'Thermometer', filename: 'thermometer', category: 'Health' },
  { name: 'Needle', filename: 'needle', category: 'Health' },
  { name: 'Bandage', filename: 'bandage', category: 'Health' },
  { name: 'Medical Bag', filename: 'medical-bag', category: 'Health' },
  { name: 'Blood Bag', filename: 'blood-bag', category: 'Health' },
  { name: 'DNA', filename: 'dna', category: 'Health' },
  { name: 'Virus', filename: 'virus', category: 'Health' },
  { name: 'Shield Plus', filename: 'shield-plus', category: 'Health' },
  { name: 'Run', filename: 'run', category: 'Health' },
  { name: 'Walk', filename: 'walk', category: 'Health' },
  { name: 'Yoga', filename: 'yoga', category: 'Health' },
  { name: 'Meditation', filename: 'meditation', category: 'Health' },
  { name: 'Weight Lifter', filename: 'weight-lifter', category: 'Health' },

  // ── Home ─────────────────────────────────────────────────
  { name: 'Home', filename: 'home', category: 'Home' },
  { name: 'Home Outline', filename: 'home-outline', category: 'Home' },
  { name: 'Sofa', filename: 'sofa', category: 'Home' },
  { name: 'Bed', filename: 'bed', category: 'Home' },
  { name: 'Lamp', filename: 'lamp', category: 'Home' },
  { name: 'Door', filename: 'door', category: 'Home' },
  { name: 'Key', filename: 'key', category: 'Home' },
  { name: 'Lightbulb', filename: 'lightbulb', category: 'Home' },
  { name: 'Lightbulb Outline', filename: 'lightbulb-outline', category: 'Home' },

  // ── Maps ─────────────────────────────────────────────────
  { name: 'Map', filename: 'map', category: 'Maps' },
  { name: 'Map Marker', filename: 'map-marker', category: 'Maps' },
  { name: 'Map Marker Outline', filename: 'map-marker-outline', category: 'Maps' },
  { name: 'Compass', filename: 'compass', category: 'Maps' },
  { name: 'Compass Outline', filename: 'compass-outline', category: 'Maps' },
  { name: 'Directions', filename: 'directions', category: 'Maps' },
  { name: 'Navigation', filename: 'navigation', category: 'Maps' },
  { name: 'Earth', filename: 'earth', category: 'Maps' },
  { name: 'Crosshairs GPS', filename: 'crosshairs-gps', category: 'Maps' },
  { name: 'Car', filename: 'car', category: 'Maps' },
  { name: 'Bus', filename: 'bus', category: 'Maps' },
  { name: 'Train', filename: 'train', category: 'Maps' },
  { name: 'Airplane', filename: 'airplane', category: 'Maps' },

  // ── Media ────────────────────────────────────────────────
  { name: 'Play', filename: 'play', category: 'Media' },
  { name: 'Pause', filename: 'pause', category: 'Media' },
  { name: 'Stop', filename: 'stop', category: 'Media' },
  { name: 'Skip Previous', filename: 'skip-previous', category: 'Media' },
  { name: 'Skip Next', filename: 'skip-next', category: 'Media' },
  { name: 'Fast Forward', filename: 'fast-forward', category: 'Media' },
  { name: 'Rewind', filename: 'rewind', category: 'Media' },
  { name: 'Volume High', filename: 'volume-high', category: 'Media' },
  { name: 'Volume Low', filename: 'volume-low', category: 'Media' },
  { name: 'Volume Off', filename: 'volume-off', category: 'Media' },
  { name: 'Microphone', filename: 'microphone', category: 'Media' },
  { name: 'Microphone Off', filename: 'microphone-off', category: 'Media' },
  { name: 'Image', filename: 'image', category: 'Media' },
  { name: 'Image Outline', filename: 'image-outline', category: 'Media' },
  { name: 'Music', filename: 'music', category: 'Media' },
  { name: 'Playlist', filename: 'playlist-music', category: 'Media' },
  { name: 'Movie', filename: 'movie', category: 'Media' },
  { name: 'Cast', filename: 'cast', category: 'Media' },
  { name: 'Radio', filename: 'radio', category: 'Media' },
  { name: 'Headphones', filename: 'headphones', category: 'Media' },

  // ── Navigation ───────────────────────────────────────────
  { name: 'Menu', filename: 'menu', category: 'Navigation' },
  { name: 'Menu Open', filename: 'menu-open', category: 'Navigation' },
  { name: 'Apps', filename: 'apps', category: 'Navigation' },
  { name: 'View Grid', filename: 'view-grid', category: 'Navigation' },
  { name: 'View List', filename: 'view-list', category: 'Navigation' },
  { name: 'Home Variant', filename: 'home-variant', category: 'Navigation' },
  { name: 'Magnify', filename: 'magnify', category: 'Navigation' },
  { name: 'Dots Horizontal', filename: 'dots-horizontal', category: 'Navigation' },
  { name: 'Close Circle', filename: 'close-circle', category: 'Navigation' },
  { name: 'Close Circle Outline', filename: 'close-circle-outline', category: 'Navigation' },
  { name: 'Check Circle', filename: 'check-circle', category: 'Navigation' },
  { name: 'Check Circle Outline', filename: 'check-circle-outline', category: 'Navigation' },

  // ── People ───────────────────────────────────────────────
  { name: 'Account', filename: 'account', category: 'People' },
  { name: 'Account Outline', filename: 'account-outline', category: 'People' },
  { name: 'Account Circle', filename: 'account-circle', category: 'People' },
  { name: 'Account Group', filename: 'account-group', category: 'People' },
  { name: 'Account Plus', filename: 'account-plus', category: 'People' },
  { name: 'Account Remove', filename: 'account-remove', category: 'People' },
  { name: 'Account Search', filename: 'account-search', category: 'People' },
  { name: 'Account Switch', filename: 'account-switch', category: 'People' },
  { name: 'Baby Face', filename: 'baby-face', category: 'People' },
  { name: 'Human Male Female', filename: 'human-male-female', category: 'People' },

  // ── Social ───────────────────────────────────────────────
  { name: 'Thumb Up Outline', filename: 'thumb-up-outline', category: 'Social' },
  { name: 'Thumb Down Outline', filename: 'thumb-down-outline', category: 'Social' },
  { name: 'Comment', filename: 'comment', category: 'Social' },
  { name: 'Comment Outline', filename: 'comment-outline', category: 'Social' },
  { name: 'Share', filename: 'share', category: 'Social' },
  { name: 'Share Outline', filename: 'share-outline', category: 'Social' },
  { name: 'Emoticon', filename: 'emoticon', category: 'Social' },
  { name: 'Emoticon Outline', filename: 'emoticon-outline', category: 'Social' },
  { name: 'Emoticon Happy', filename: 'emoticon-happy', category: 'Social' },
  { name: 'Emoticon Sad', filename: 'emoticon-sad', category: 'Social' },

  // ── System ───────────────────────────────────────────────
  { name: 'Information', filename: 'information', category: 'System' },
  { name: 'Information Outline', filename: 'information-outline', category: 'System' },
  { name: 'Help Circle', filename: 'help-circle', category: 'System' },
  { name: 'Help Circle Outline', filename: 'help-circle-outline', category: 'System' },
  { name: 'Alert', filename: 'alert', category: 'System' },
  { name: 'Alert Outline', filename: 'alert-outline', category: 'System' },
  { name: 'Alert Circle', filename: 'alert-circle', category: 'System' },
  { name: 'Alert Circle Outline', filename: 'alert-circle-outline', category: 'System' },
  { name: 'Check Bold', filename: 'check-bold', category: 'System' },
  { name: 'Close Thick', filename: 'close-thick', category: 'System' },
  { name: 'Eye', filename: 'eye', category: 'System' },
  { name: 'Eye Off', filename: 'eye-off', category: 'System' },
  { name: 'Eye Outline', filename: 'eye-outline', category: 'System' },
  { name: 'Loading', filename: 'loading', category: 'System' },
  { name: 'Sync', filename: 'sync', category: 'System' },
  { name: 'Clock', filename: 'clock', category: 'System' },
  { name: 'Clock Outline', filename: 'clock-outline', category: 'System' },
  { name: 'Calendar', filename: 'calendar', category: 'System' },
  { name: 'Calendar Outline', filename: 'calendar-outline', category: 'System' },
  { name: 'Shield Check', filename: 'shield-check', category: 'System' },

  // ── Weather ──────────────────────────────────────────────
  { name: 'Weather Sunny', filename: 'weather-sunny', category: 'Weather' },
  { name: 'Weather Night', filename: 'weather-night', category: 'Weather' },
  { name: 'Weather Cloudy', filename: 'weather-cloudy', category: 'Weather' },
  { name: 'Weather Rainy', filename: 'weather-rainy', category: 'Weather' },
  { name: 'Weather Snowy', filename: 'weather-snowy', category: 'Weather' },
  { name: 'Weather Lightning', filename: 'weather-lightning', category: 'Weather' },
  { name: 'Thermometer Low', filename: 'thermometer-low', category: 'Weather' },
  { name: 'Thermometer High', filename: 'thermometer-high', category: 'Weather' },
]

export const ICON_MAP = new Map(ICONS.map((i) => [i.filename, i]))
