// Icon catalog — Wonderland DS icons (camelCase names)

export interface IconEntry {
  name: string
  /** DS icon folder name in camelCase */
  filename: string
  category: string
}

export const ICON_CATEGORIES = [
  'Actions',
  'Arrows',
  'Communication',
  'Commerce',
  'Content',
  'Device',
  'Health',
  'Home',
  'Maps',
  'Media',
  'Navigation',
  'People',
  'Social',
  'System',
  'Alice',
] as const

export type IconCategory = (typeof ICON_CATEGORIES)[number]

export const ICONS: IconEntry[] = [
  // ── Actions ──────────────────────────────────────────────
  { name: 'Add',           filename: 'add',           category: 'Actions' },
  { name: 'Add List',      filename: 'addList',        category: 'Actions' },
  { name: 'Add Note',      filename: 'addNote',        category: 'Actions' },
  { name: 'Archive',       filename: 'archive',        category: 'Actions' },
  { name: 'Block',         filename: 'block',          category: 'Actions' },
  { name: 'Clear',         filename: 'clear',          category: 'Actions' },
  { name: 'Close',         filename: 'close',          category: 'Actions' },
  { name: 'Copy',          filename: 'copy',           category: 'Actions' },
  { name: 'Delete',        filename: 'delete',         category: 'Actions' },
  { name: 'Download',      filename: 'download',       category: 'Actions' },
  { name: 'Draggable',     filename: 'draggable',      category: 'Actions' },
  { name: 'Edit',          filename: 'edit',           category: 'Actions' },
  { name: 'Flag',          filename: 'flag',           category: 'Actions' },
  { name: 'Like',          filename: 'like',           category: 'Actions' },
  { name: 'Dislike',       filename: 'dislike',        category: 'Actions' },
  { name: 'Lock',          filename: 'lock',           category: 'Actions' },
  { name: 'Unlock',        filename: 'unlock',         category: 'Actions' },
  { name: 'Logout',        filename: 'logout',         category: 'Actions' },
  { name: 'Magic',         filename: 'magic',          category: 'Actions' },
  { name: 'Pin',           filename: 'pin',            category: 'Actions' },
  { name: 'Power',         filename: 'power',          category: 'Actions' },
  { name: 'Print',         filename: 'print',          category: 'Actions' },
  { name: 'Reply',         filename: 'reply',          category: 'Actions' },
  { name: 'Save',          filename: 'save',           category: 'Actions' },
  { name: 'Search',        filename: 'search',         category: 'Actions' },
  { name: 'Settings',      filename: 'settings',       category: 'Actions' },
  { name: 'Share Android', filename: 'shareAndroid',   category: 'Actions' },
  { name: 'Share iOS',     filename: 'shareiOS',       category: 'Actions' },
  { name: 'Sorting',       filename: 'sorting',        category: 'Actions' },
  { name: 'Trash',         filename: 'trash',          category: 'Actions' },
  { name: 'Update',        filename: 'update',         category: 'Actions' },
  { name: 'Upload',        filename: 'upload',         category: 'Actions' },
  { name: 'Menu Filter',   filename: 'menuFilter',     category: 'Actions' },
  { name: 'Menu Fries',    filename: 'menuFries',      category: 'Actions' },
  { name: 'Menu Hamburger',filename: 'menuHamburger',  category: 'Actions' },
  { name: 'Menu Kebab',    filename: 'menuKebab',      category: 'Actions' },
  { name: 'Menu Square',   filename: 'menuSquare',     category: 'Actions' },

  // ── Arrows ───────────────────────────────────────────────
  { name: 'Arrow Up',                  filename: 'arrowUp',               category: 'Arrows' },
  { name: 'Arrow Down',                filename: 'arrowDown',             category: 'Arrows' },
  { name: 'Arrow Left',                filename: 'arrowLeft',             category: 'Arrows' },
  { name: 'Arrow Right',               filename: 'arrowRight',            category: 'Arrows' },
  { name: 'Arrow Up Left',             filename: 'arrowUpLeft',           category: 'Arrows' },
  { name: 'Arrow Up Right',            filename: 'arrowUpRight',          category: 'Arrows' },
  { name: 'Arrow Down Left',           filename: 'arrowDownLeft',         category: 'Arrows' },
  { name: 'Arrow Down Right',          filename: 'arrowDownRight',        category: 'Arrows' },
  { name: 'Arrow Upper Left',          filename: 'arrowUpperLeft',        category: 'Arrows' },
  { name: 'Arrow Upper Right',         filename: 'arrowUpperRight',       category: 'Arrows' },
  { name: 'Arrow Swap',                filename: 'arrowSwap',             category: 'Arrows' },
  { name: 'Arrow Redo',                filename: 'arrowRedo',             category: 'Arrows' },
  { name: 'Arrow Repetition',          filename: 'arrowRepetition',       category: 'Arrows' },
  { name: 'Arrow Collapse',            filename: 'arrowCollapse',         category: 'Arrows' },
  { name: 'Arrow Expand 1',            filename: 'arrowExpand1',          category: 'Arrows' },
  { name: 'Arrow Expand 2',            filename: 'arrowExpand2',          category: 'Arrows' },
  { name: 'Chevron Up',                filename: 'chevronArrowUp',        category: 'Arrows' },
  { name: 'Chevron Down',              filename: 'chevronArrowDown',      category: 'Arrows' },
  { name: 'Chevron Left',              filename: 'chevronArrowLeft',      category: 'Arrows' },
  { name: 'Chevron Right',             filename: 'chevronArrowRight',     category: 'Arrows' },
  { name: 'Double Chevron Up',         filename: 'doubleChevronArrowUp',  category: 'Arrows' },
  { name: 'Double Chevron Down',       filename: 'doubleChevronArrowDown',category: 'Arrows' },
  { name: 'Double Chevron Left',       filename: 'doubleChevronArrowLeft',category: 'Arrows' },
  { name: 'Double Chevron Right',      filename: 'doubleChevronArrowRight',category: 'Arrows' },

  // ── Communication ────────────────────────────────────────
  { name: 'Bell',          filename: 'bell',           category: 'Communication' },
  { name: 'Chat',          filename: 'chat',           category: 'Communication' },
  { name: 'Chat Read',     filename: 'chatRead',       category: 'Communication' },
  { name: 'Chat Sent',     filename: 'chatSent',       category: 'Communication' },
  { name: 'Email',         filename: 'email',          category: 'Communication' },
  { name: 'Mail Box',      filename: 'mailBox',        category: 'Communication' },
  { name: 'Meeting',       filename: 'meeting',        category: 'Communication' },
  { name: 'Megaphone',     filename: 'megaphone',      category: 'Communication' },
  { name: 'Mention',       filename: 'mention',        category: 'Communication' },
  { name: 'Mic Off',       filename: 'micOff',         category: 'Communication' },
  { name: 'Mic On',        filename: 'micOn',          category: 'Communication' },
  { name: 'Phone',         filename: 'phone',          category: 'Communication' },
  { name: 'Phone Filled',  filename: 'PhoneFilled',    category: 'Communication' },
  { name: 'Phone Down',    filename: 'phoneDownFilled',category: 'Communication' },
  { name: 'Phone Speak',   filename: 'phoneSpeak',     category: 'Communication' },
  { name: 'Send 1',        filename: 'send1',          category: 'Communication' },
  { name: 'Send 2',        filename: 'send2',          category: 'Communication' },
  { name: 'Video Message', filename: 'videoMessage',   category: 'Communication' },
  { name: 'Video Off',     filename: 'videoOff',       category: 'Communication' },
  { name: 'Video On',      filename: 'videoOn',        category: 'Communication' },
  { name: 'WhatsApp',      filename: 'whatsapp',       category: 'Communication' },

  // ── Commerce ─────────────────────────────────────────────
  { name: 'Barcode',       filename: 'barcode',        category: 'Commerce' },
  { name: 'Credit Card',   filename: 'creditCard',     category: 'Commerce' },
  { name: 'Money',         filename: 'money',          category: 'Commerce' },
  { name: 'Pix',           filename: 'pix',            category: 'Commerce' },
  { name: 'Refund Money',  filename: 'refundMoney',    category: 'Commerce' },
  { name: 'Shop',          filename: 'shop',           category: 'Commerce' },
  { name: 'Ticket',        filename: 'ticket',         category: 'Commerce' },
  { name: 'Gift',          filename: 'gift',           category: 'Commerce' },
  { name: 'Diamond',       filename: 'diamond',        category: 'Commerce' },

  // ── Content ──────────────────────────────────────────────
  { name: 'Asterisk',      filename: 'asterisk',       category: 'Content' },
  { name: 'Attachment',    filename: 'attachment',     category: 'Content' },
  { name: 'Bold',          filename: 'bold',           category: 'Content' },
  { name: 'Bullets',       filename: 'bullets',        category: 'Content' },
  { name: 'Dashboard',     filename: 'dashboard',      category: 'Content' },
  { name: 'Flowchart',     filename: 'flowchart',      category: 'Content' },
  { name: 'Hashtag',       filename: 'hashtag',        category: 'Content' },
  { name: 'Italic',        filename: 'italic',         category: 'Content' },
  { name: 'Link',          filename: 'link',           category: 'Content' },
  { name: 'Numbering',     filename: 'numbering',      category: 'Content' },
  { name: 'Paper',         filename: 'paper',          category: 'Content' },
  { name: 'Script',        filename: 'script',         category: 'Content' },
  { name: 'Strikethrough', filename: 'strikethrough',  category: 'Content' },
  { name: 'Underline',     filename: 'underline',      category: 'Content' },

  // ── Device ───────────────────────────────────────────────
  { name: 'Camera',        filename: 'camera',         category: 'Device' },
  { name: 'Flip Camera',   filename: 'flipCamera',     category: 'Device' },
  { name: 'Cell',          filename: 'cell',           category: 'Device' },
  { name: 'Wifi Off',      filename: 'wifiOff',        category: 'Device' },
  { name: 'Wifi On',       filename: 'wifiOn',         category: 'Device' },
  { name: 'Picture',       filename: 'picture',        category: 'Device' },
  { name: 'No Picture',    filename: 'noPicture',      category: 'Device' },

  // ── Health ───────────────────────────────────────────────
  { name: 'Baby',               filename: 'baby',              category: 'Health' },
  { name: 'Bandaid',            filename: 'bandaid',           category: 'Health' },
  { name: 'Blood',              filename: 'blood',             category: 'Health' },
  { name: 'Body Filled',        filename: 'bodyFilled',        category: 'Health' },
  { name: 'Body Outlined',      filename: 'bodyOutlined',      category: 'Health' },
  { name: 'Care Prioritization',filename: 'carePrioritization',category: 'Health' },
  { name: 'Check Filled',       filename: 'checkFilled',       category: 'Health' },
  { name: 'Check Outlined',     filename: 'checkOutlined',     category: 'Health' },
  { name: 'DNA',                filename: 'dna',               category: 'Health' },
  { name: 'Heart Filled',       filename: 'heartFilled',       category: 'Health' },
  { name: 'Heart Outlined',     filename: 'heartOutlined',     category: 'Health' },
  { name: 'Hospital',           filename: 'hospital',          category: 'Health' },
  { name: 'Lab',                filename: 'lab',               category: 'Health' },
  { name: 'Microscope',         filename: 'microscope',        category: 'Health' },
  { name: 'Mindfulness',        filename: 'mindfulness',       category: 'Health' },
  { name: 'Pill',               filename: 'pill',              category: 'Health' },
  { name: 'Pulse',              filename: 'pulse',             category: 'Health' },
  { name: 'Sport',              filename: 'sport',             category: 'Health' },
  { name: 'Stethoscope',        filename: 'stethoscope',       category: 'Health' },
  { name: 'Thermometer',        filename: 'thermometer',       category: 'Health' },
  { name: 'Vaccine',            filename: 'vaccine',           category: 'Health' },
  { name: 'Weight',             filename: 'weight',            category: 'Health' },

  // ── Home ─────────────────────────────────────────────────
  { name: 'Bathroom',     filename: 'bathroom',       category: 'Home' },
  { name: 'Bed',          filename: 'bed',            category: 'Home' },
  { name: 'Casa Alice',   filename: 'casaAlice',      category: 'Home' },
  { name: 'Home Filled',  filename: 'homeFilled',     category: 'Home' },
  { name: 'Home Outlined',filename: 'homeOutlined',   category: 'Home' },
  { name: 'House',        filename: 'house',          category: 'Home' },
  { name: 'Shower',       filename: 'shower',         category: 'Home' },

  // ── Maps ─────────────────────────────────────────────────
  { name: 'Airplane',     filename: 'airplane',       category: 'Maps' },
  { name: 'Earth',        filename: 'earth',          category: 'Maps' },
  { name: 'Local Pin',    filename: 'localPin',       category: 'Maps' },

  // ── Media ────────────────────────────────────────────────
  { name: 'Pause',            filename: 'pause',           category: 'Media' },
  { name: 'Pause Circle',     filename: 'pauseCircle',     category: 'Media' },
  { name: 'Picture In Picture',filename: 'pictureInPicture',category: 'Media' },
  { name: 'Play',             filename: 'play',            category: 'Media' },
  { name: 'Play Circle',      filename: 'playCircle',      category: 'Media' },
  { name: 'Playlist',         filename: 'playlist',        category: 'Media' },
  { name: 'Stop',             filename: 'stop',            category: 'Media' },
  { name: 'Stop Circle',      filename: 'stopCircle',      category: 'Media' },
  { name: 'Volume Off',       filename: 'volumeOff',       category: 'Media' },
  { name: 'Volume On',        filename: 'volumeOn',        category: 'Media' },
  { name: 'Repeat',           filename: 'repeat',          category: 'Media' },

  // ── Navigation ───────────────────────────────────────────
  { name: 'Floater',      filename: 'floater',        category: 'Navigation' },

  // ── People ───────────────────────────────────────────────
  { name: 'Accessibility',     filename: 'accessibility',   category: 'People' },
  { name: 'Add User',          filename: 'addUser',         category: 'People' },
  { name: 'Family',            filename: 'family',          category: 'People' },
  { name: 'Ghost',             filename: 'ghost',           category: 'People' },
  { name: 'Hand',              filename: 'hand',            category: 'People' },
  { name: 'Hand Tool Closed',  filename: 'handToolClosed',  category: 'People' },
  { name: 'Hand Tool Opened',  filename: 'handToolOpened',  category: 'People' },
  { name: 'No Team',           filename: 'noTeam',          category: 'People' },
  { name: 'Team',              filename: 'team',            category: 'People' },
  { name: 'User',              filename: 'user',            category: 'People' },

  // ── Social ───────────────────────────────────────────────
  { name: 'Dislike',       filename: 'dislike',        category: 'Social' },
  { name: 'Heart Filled',  filename: 'heartFilled',    category: 'Social' },
  { name: 'Heart Outlined',filename: 'heartOutlined',  category: 'Social' },
  { name: 'Like',          filename: 'like',           category: 'Social' },
  { name: 'Reaction Smile',filename: 'reactionSmile',  category: 'Social' },
  { name: 'Star Filled',   filename: 'starFilled',     category: 'Social' },
  { name: 'Star Outlined', filename: 'starOutlined',   category: 'Social' },
  { name: 'Trophy',        filename: 'trophy',         category: 'Social' },

  // ── System ───────────────────────────────────────────────
  { name: 'Alert Circle Filled',  filename: 'alertCircleFilled',   category: 'System' },
  { name: 'Alert Circle Outlined',filename: 'alertCircleOutlined', category: 'System' },
  { name: 'Alert Rotating Light', filename: 'alertRotatinLight',   category: 'System' },
  { name: 'Alert Triangle',       filename: 'alertTriangle',       category: 'System' },
  { name: 'Atomic',               filename: 'atomic',              category: 'System' },
  { name: 'Bug',                  filename: 'bug',                 category: 'System' },
  { name: 'Calculator',           filename: 'calculator',          category: 'System' },
  { name: 'Calendar',             filename: 'calendar',            category: 'System' },
  { name: 'Calendar Add',         filename: 'calendarAdd',         category: 'System' },
  { name: 'Circle Fill',          filename: 'circleFill',          category: 'System' },
  { name: 'Clock',                filename: 'clock',               category: 'System' },
  { name: 'Crono',                filename: 'crono',               category: 'System' },
  { name: 'Day',                  filename: 'day',                 category: 'System' },
  { name: 'Eye Closed',           filename: 'eyeClosed',           category: 'System' },
  { name: 'Eye Hide',             filename: 'eyeHide',             category: 'System' },
  { name: 'Eye Show',             filename: 'eyeShow',             category: 'System' },
  { name: 'Folder',               filename: 'folder',              category: 'System' },
  { name: 'Goal',                 filename: 'goal',                category: 'System' },
  { name: 'Help',                 filename: 'help',                category: 'System' },
  { name: 'Historic',             filename: 'historic',            category: 'System' },
  { name: 'ID Card',              filename: 'idCard',              category: 'System' },
  { name: 'Info',                 filename: 'info',                category: 'System' },
  { name: 'Load',                 filename: 'load',                category: 'System' },
  { name: 'Monitoring Activity',  filename: 'monitoringActivity',  category: 'System' },
  { name: 'Night',                filename: 'night',               category: 'System' },
  { name: 'Notification Card',    filename: 'notificationCard',    category: 'System' },
  { name: 'Plan',                 filename: 'plan',                category: 'System' },
  { name: 'Priority High',        filename: 'priorityHigh',        category: 'System' },
  { name: 'Priority Low',         filename: 'priorityLow',         category: 'System' },
  { name: 'Priority Medium',      filename: 'priorityMedium',      category: 'System' },
  { name: 'Priority Trivial',     filename: 'priorityTrivial',     category: 'System' },
  { name: 'Protocol',             filename: 'protocol',            category: 'System' },
  { name: 'Ruler',                filename: 'ruler',               category: 'System' },
  { name: 'Score',                filename: 'score',               category: 'System' },
  { name: 'Success',              filename: 'success',             category: 'System' },
  { name: 'Target',               filename: 'target',              category: 'System' },
  { name: 'Task Check',           filename: 'taskCheck',           category: 'System' },

  // ── Alice ────────────────────────────────────────────────
  { name: 'AI Ring',      filename: 'aiRing',         category: 'Alice' },
  { name: 'Alice Agora',  filename: 'aliceAgora',     category: 'Alice' },
  { name: 'Tyto',         filename: 'tyto',           category: 'Alice' },
  { name: 'Rocket',       filename: 'rocket',         category: 'Alice' },
  { name: 'Pillar',       filename: 'pillar',         category: 'Alice' },
  { name: 'Pillars',      filename: 'pillars',        category: 'Alice' },
]

export const ICON_MAP = new Map(ICONS.map((i) => [i.filename, i]))
